### ISSUE TITLE
Installation fails with pip 10

### ISSUE THREAD

**Issue by chosak** [cfpb/ccdb5-api#72]
Installation of this package with pip 10 fails due to the use of `pip.req` [here](https://github.com/cfpb/ccdb5-api/blob/6270754f81d4d206d364c0d11be0a5a1cde3fcbe/setup.py#L21) in setup.py.

```sh
$ pip --version
pip 10.0.1 from ...
$ pip install git+https://github.com/cfpb/ccdb5-api.git@v1.0.5#egg=ccdb5-api
Collecting ccdb5-api from git+https://github.com/cfpb/ccdb5-api.git@v1.0.5#egg=ccdb5-api
  Cloning https://github.com/cfpb/ccdb5-api.git (to revision v1.0.5) to /private/var/folders/gg/wxm3673x2356ll65n0xbm_7r0000gn/T/pip-install-CacAhx/ccdb5-api
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gg/wxm3673x2356ll65n0xbm_7r0000gn/T/pip-install-CacAhx/ccdb5-api/setup.py", line 32, in <module>
        install_requires = parse_requirements()
      File "/private/var/folders/gg/wxm3673x2356ll65n0xbm_7r0000gn/T/pip-install-CacAhx/ccdb5-api/setup.py", line 21, in parse_requirements
        requirements = pip.req.parse_requirements(
    AttributeError: 'module' object has no attribute 'req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gg/wxm3673x2356ll65n0xbm_7r0000gn/T/pip-install-CacAhx/ccdb5-api/
```

See [this related discussion](https://stackoverflow.com/a/49837302) about use of pip internals; an alternative approach would be to define requirements in the setup.py `install_requires` instead of in requirements.txt. See related setuptools documentation [here](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies).

**Comment by chosak** [comment]
This is fixed by the commit in #73:

```sh
$ pip install git+https://github.com/cfpb/ccdb5-api.git@a7a77ff#egg=ccdb5-api
```

This repository can now be successfully installed with pip 10.
